// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // 👇 TAMBAHKAN BARIS INI UNTUK MENJALANKAN SEED
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Gunakan DIRECT_URL untuk CLI/Migrasi (jika tidak ada, fallback ke DATABASE_URL)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});